// =============================================================================
// lib/pdf/generate-timecard.ts
// Server-side PDF generation for a single timecard using @react-pdf/renderer.
//
// Layout:
//   - Header:        Norwich Public Schools / TIMECARD / Program name, account, pay period
//   - Staff block:   Name, school, address
//   - Hours table:   Date | Time In | Time Out | Total Hours
//   - Signature block: Staff typed name + timestamp; Signee typed name + timestamp
//   - Footer:        Generated by Norwich Public Schools Timesheet System / timestamp
//
// Returns a Buffer suitable for storage (Supabase Storage) or HTTP response.
// =============================================================================

import React from 'react'
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  renderToBuffer,
  Font,
} from '@react-pdf/renderer'
import { format, parseISO } from 'date-fns'

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface TimecardEntry {
  work_date: string   // YYYY-MM-DD
  time_in: string     // HH:MM or HH:MM:SS
  time_out: string    // HH:MM or HH:MM:SS
  total_hours: number
}

export interface TimecardPdfData {
  // Program info
  programName: string
  accountNumber: string
  // Pay period info
  payPeriodLabel: string
  payPeriodStart: string  // YYYY-MM-DD
  payPeriodEnd: string    // YYYY-MM-DD
  // Staff info
  staffName: string
  staffSchool: string
  staffAddress: string
  // Time entries
  entries: TimecardEntry[]
  // Signatures
  staffSignature: string | null
  staffSignedAt: string | null    // ISO timestamp
  signeeName: string | null
  signeeSignature: string | null
  signeeSignedAt: string | null   // ISO timestamp
  // NTL rate (optional — shown in footer summary)
  ntlRate?: number | null
  /** Timecard status for display */
  status: 'draft' | 'submitted' | 'signed' | 'reopen_requested' | 'reopened'
}

// ---------------------------------------------------------------------------
// Styles
// ---------------------------------------------------------------------------

const colors = {
  navy: '#1a3a5c',
  navyLight: '#e8eef4',
  accent: '#2563eb',
  border: '#d1d5db',
  tableHeader: '#374151',
  tableHeaderBg: '#f3f4f6',
  tableAlt: '#f9fafb',
  text: '#111827',
  textMuted: '#6b7280',
  signatureBg: '#fafafa',
  footerText: '#9ca3af',
  statusSigned: '#065f46',
  statusSignedBg: '#d1fae5',
  statusDraft: '#92400e',
  statusDraftBg: '#fef3c7',
  statusSubmitted: '#1e40af',
  statusSubmittedBg: '#dbeafe',
}

const styles = StyleSheet.create({
  page: {
    fontFamily: 'Helvetica',
    fontSize: 10,
    color: colors.text,
    paddingTop: 40,
    paddingBottom: 50,
    paddingHorizontal: 45,
  },

  // ---- Header ----
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    borderBottomWidth: 2,
    borderBottomColor: colors.navy,
    paddingBottom: 12,
    marginBottom: 16,
  },
  headerLeft: {
    flex: 1,
  },
  orgName: {
    fontSize: 18,
    fontFamily: 'Helvetica-Bold',
    color: colors.navy,
    letterSpacing: 0.3,
  },
  docTitle: {
    fontSize: 11,
    fontFamily: 'Helvetica',
    color: colors.textMuted,
    marginTop: 2,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  headerRight: {
    alignItems: 'flex-end',
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 4,
    fontSize: 9,
    fontFamily: 'Helvetica-Bold',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },

  // ---- Program info block ----
  infoGrid: {
    flexDirection: 'row',
    backgroundColor: colors.navyLight,
    borderRadius: 4,
    padding: 12,
    marginBottom: 16,
    gap: 24,
  },
  infoCell: {
    flex: 1,
  },
  infoLabel: {
    fontSize: 8,
    fontFamily: 'Helvetica-Bold',
    color: colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  infoValue: {
    fontSize: 10,
    fontFamily: 'Helvetica-Bold',
    color: colors.text,
  },
  infoValueNormal: {
    fontSize: 10,
    color: colors.text,
  },

  // ---- Section label ----
  sectionLabel: {
    fontSize: 8,
    fontFamily: 'Helvetica-Bold',
    color: colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 6,
    marginTop: 4,
  },

  // ---- Staff info block ----
  staffBlock: {
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 4,
    marginBottom: 16,
    overflow: 'hidden',
  },
  staffCell: {
    flex: 1,
    padding: 10,
    borderRightWidth: 1,
    borderRightColor: colors.border,
  },
  staffCellLast: {
    flex: 2,
    padding: 10,
  },
  staffLabel: {
    fontSize: 8,
    fontFamily: 'Helvetica-Bold',
    color: colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 3,
  },
  staffValue: {
    fontSize: 10,
    color: colors.text,
  },

  // ---- Hours table ----
  table: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 4,
    marginBottom: 16,
    overflow: 'hidden',
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: colors.tableHeaderBg,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    minHeight: 22,
  },
  tableRowAlt: {
    backgroundColor: colors.tableAlt,
  },
  tableRowLast: {
    borderBottomWidth: 0,
  },
  colDate: {
    width: '30%',
    padding: '5 8',
  },
  colTimeIn: {
    width: '20%',
    padding: '5 8',
    borderLeftWidth: 1,
    borderLeftColor: colors.border,
  },
  colTimeOut: {
    width: '20%',
    padding: '5 8',
    borderLeftWidth: 1,
    borderLeftColor: colors.border,
  },
  colHours: {
    width: '15%',
    padding: '5 8',
    borderLeftWidth: 1,
    borderLeftColor: colors.border,
    alignItems: 'flex-end',
  },
  colNotes: {
    flex: 1,
    padding: '5 8',
    borderLeftWidth: 1,
    borderLeftColor: colors.border,
  },
  tableHeaderText: {
    fontSize: 8,
    fontFamily: 'Helvetica-Bold',
    color: colors.tableHeader,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  tableCellText: {
    fontSize: 9,
    color: colors.text,
  },
  tableCellTextRight: {
    fontSize: 9,
    color: colors.text,
    textAlign: 'right',
  },

  // ---- Totals row ----
  totalsRow: {
    flexDirection: 'row',
    backgroundColor: colors.navy,
    borderTopWidth: 1,
    borderTopColor: colors.navy,
    minHeight: 24,
  },
  totalsLabelCell: {
    width: '70%',
    padding: '6 8',
    alignItems: 'flex-end',
  },
  totalsValueCell: {
    width: '15%',
    padding: '6 8',
    alignItems: 'flex-end',
    borderLeftWidth: 1,
    borderLeftColor: '#3b5c8a',
  },
  totalsEmptyCell: {
    flex: 1,
    padding: '6 8',
    borderLeftWidth: 1,
    borderLeftColor: '#3b5c8a',
  },
  totalsLabelText: {
    fontSize: 9,
    fontFamily: 'Helvetica-Bold',
    color: '#ffffff',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  totalsValueText: {
    fontSize: 9,
    fontFamily: 'Helvetica-Bold',
    color: '#ffffff',
    textAlign: 'right',
  },

  // ---- Earnings summary ----
  earningsRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginBottom: 16,
    marginTop: 4,
  },
  earningsBox: {
    backgroundColor: colors.navyLight,
    borderRadius: 4,
    padding: '8 12',
    flexDirection: 'row',
    gap: 16,
  },
  earningsItem: {
    alignItems: 'flex-end',
  },
  earningsLabel: {
    fontSize: 8,
    color: colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    marginBottom: 2,
  },
  earningsValue: {
    fontSize: 11,
    fontFamily: 'Helvetica-Bold',
    color: colors.navy,
  },

  // ---- Signature block ----
  signaturesContainer: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: 16,
  },
  signatureBox: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 4,
    overflow: 'hidden',
  },
  signatureHeader: {
    backgroundColor: colors.tableHeaderBg,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    padding: '6 10',
  },
  signatureHeaderText: {
    fontSize: 8,
    fontFamily: 'Helvetica-Bold',
    color: colors.tableHeader,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  signatureBody: {
    padding: 12,
    backgroundColor: colors.signatureBg,
    minHeight: 60,
  },
  signatureNameLabel: {
    fontSize: 8,
    color: colors.textMuted,
    marginBottom: 4,
  },
  signatureName: {
    fontSize: 13,
    fontFamily: 'Helvetica-Oblique',
    color: colors.navy,
    marginBottom: 8,
  },
  signatureTimestamp: {
    fontSize: 8,
    color: colors.textMuted,
  },
  signaturePending: {
    fontSize: 9,
    color: colors.textMuted,
    fontFamily: 'Helvetica-Oblique',
    marginTop: 8,
  },

  // ---- Footer ----
  footer: {
    position: 'absolute',
    bottom: 20,
    left: 45,
    right: 45,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  footerText: {
    fontSize: 8,
    color: colors.footerText,
  },
  footerRight: {
    alignItems: 'flex-end',
  },
  pageNumber: {
    fontSize: 8,
    color: colors.footerText,
  },
})

// ---------------------------------------------------------------------------
// Formatting helpers
// ---------------------------------------------------------------------------

function fmtDate(iso: string): string {
  try {
    return format(parseISO(iso), 'EEE, MMM d, yyyy')
  } catch {
    return iso
  }
}

function fmtDateShort(iso: string): string {
  try {
    return format(parseISO(iso), 'MMM d, yyyy')
  } catch {
    return iso
  }
}

function fmtTime(t: string): string {
  // Accepts HH:MM or HH:MM:SS → formats as "h:mm AM/PM"
  try {
    const [hStr, mStr] = t.split(':')
    const h = parseInt(hStr, 10)
    const m = parseInt(mStr, 10)
    const ampm = h >= 12 ? 'PM' : 'AM'
    const h12 = h % 12 === 0 ? 12 : h % 12
    return `${h12}:${String(m).padStart(2, '0')} ${ampm}`
  } catch {
    return t
  }
}

function fmtHours(h: number): string {
  return h.toFixed(2)
}

function fmtTimestamp(iso: string | null): string {
  if (!iso) return ''
  try {
    return format(new Date(iso), 'MMM d, yyyy h:mm a')
  } catch {
    return iso
  }
}

function fmtCurrency(amount: number): string {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
  }).format(amount)
}

function getStatusColors(status: TimecardPdfData['status']): { bg: string; text: string } {
  switch (status) {
    case 'signed':
      return { bg: colors.statusSignedBg, text: colors.statusSigned }
    case 'submitted':
      return { bg: colors.statusSubmittedBg, text: colors.statusSubmitted }
    default:
      return { bg: colors.statusDraftBg, text: colors.statusDraft }
  }
}

function getStatusLabel(status: TimecardPdfData['status']): string {
  switch (status) {
    case 'draft': return 'Draft'
    case 'submitted': return 'Submitted'
    case 'signed': return 'Signed'
    case 'reopen_requested': return 'Reopen Requested'
    case 'reopened': return 'Reopened'
    default: return status
  }
}

// ---------------------------------------------------------------------------
// React-PDF Document component
// ---------------------------------------------------------------------------

function TimecardDocument({ data }: { data: TimecardPdfData }) {
  const totalHours = data.entries.reduce((sum, e) => sum + e.total_hours, 0)
  const earnings = data.ntlRate ? totalHours * data.ntlRate : null
  const statusColors = getStatusColors(data.status)
  const generatedAt = format(new Date(), 'MMM d, yyyy h:mm a')

  return React.createElement(
    Document,
    {
      title: `Timecard — ${data.staffName} — ${data.payPeriodLabel}`,
      author: 'Norwich Public Schools Timecard System',
      subject: `${data.programName} Timecard`,
      creator: 'NPS Timecards',
    },
    React.createElement(
      Page,
      { size: 'LETTER', style: styles.page },

      // ---- Header ----
      React.createElement(
        View,
        { style: styles.headerContainer },
        React.createElement(
          View,
          { style: styles.headerLeft },
          React.createElement(Text, { style: styles.orgName }, 'Norwich Public Schools'),
          React.createElement(Text, { style: styles.docTitle }, 'Employee Timecard')
        ),
        React.createElement(
          View,
          { style: styles.headerRight },
          React.createElement(
            Text,
            {
              style: [
                styles.statusBadge,
                { backgroundColor: statusColors.bg, color: statusColors.text },
              ],
            },
            getStatusLabel(data.status)
          )
        )
      ),

      // ---- Program / Pay Period Info Grid ----
      React.createElement(
        View,
        { style: styles.infoGrid },
        React.createElement(
          View,
          { style: styles.infoCell },
          React.createElement(Text, { style: styles.infoLabel }, 'Program'),
          React.createElement(Text, { style: styles.infoValue }, data.programName)
        ),
        React.createElement(
          View,
          { style: styles.infoCell },
          React.createElement(Text, { style: styles.infoLabel }, 'Account Number'),
          React.createElement(Text, { style: styles.infoValueNormal }, data.accountNumber)
        ),
        React.createElement(
          View,
          { style: styles.infoCell },
          React.createElement(Text, { style: styles.infoLabel }, 'Pay Period'),
          React.createElement(Text, { style: styles.infoValueNormal }, data.payPeriodLabel)
        ),
        React.createElement(
          View,
          { style: styles.infoCell },
          React.createElement(Text, { style: styles.infoLabel }, 'Dates'),
          React.createElement(
            Text,
            { style: styles.infoValueNormal },
            `${fmtDateShort(data.payPeriodStart)} – ${fmtDateShort(data.payPeriodEnd)}`
          )
        )
      ),

      // ---- Staff Info Block ----
      React.createElement(Text, { style: styles.sectionLabel }, 'Staff Information'),
      React.createElement(
        View,
        { style: styles.staffBlock },
        React.createElement(
          View,
          { style: styles.staffCell },
          React.createElement(Text, { style: styles.staffLabel }, 'Employee Name'),
          React.createElement(Text, { style: styles.staffValue }, data.staffName)
        ),
        React.createElement(
          View,
          { style: styles.staffCell },
          React.createElement(Text, { style: styles.staffLabel }, 'School / Work Site'),
          React.createElement(Text, { style: styles.staffValue }, data.staffSchool)
        ),
        React.createElement(
          View,
          { style: styles.staffCellLast },
          React.createElement(Text, { style: styles.staffLabel }, 'Address'),
          React.createElement(Text, { style: styles.staffValue }, data.staffAddress || '—')
        )
      ),

      // ---- Hours Table ----
      React.createElement(Text, { style: styles.sectionLabel }, 'Hours Worked'),
      React.createElement(
        View,
        { style: styles.table },
        // Table header
        React.createElement(
          View,
          { style: styles.tableHeader },
          React.createElement(
            View,
            { style: styles.colDate },
            React.createElement(Text, { style: styles.tableHeaderText }, 'Date')
          ),
          React.createElement(
            View,
            { style: styles.colTimeIn },
            React.createElement(Text, { style: styles.tableHeaderText }, 'Time In')
          ),
          React.createElement(
            View,
            { style: styles.colTimeOut },
            React.createElement(Text, { style: styles.tableHeaderText }, 'Time Out')
          ),
          React.createElement(
            View,
            { style: styles.colHours },
            React.createElement(Text, { style: styles.tableHeaderText }, 'Hours')
          ),
          React.createElement(
            View,
            { style: styles.colNotes },
            React.createElement(Text, { style: styles.tableHeaderText }, 'Notes')
          )
        ),
        // Data rows
        ...data.entries.map((entry, index) =>
          React.createElement(
            View,
            {
              key: index,
              style: [
                styles.tableRow,
                index % 2 === 1 ? styles.tableRowAlt : {},
                index === data.entries.length - 1 ? styles.tableRowLast : {},
              ],
            },
            React.createElement(
              View,
              { style: styles.colDate },
              React.createElement(Text, { style: styles.tableCellText }, fmtDate(entry.work_date))
            ),
            React.createElement(
              View,
              { style: styles.colTimeIn },
              React.createElement(Text, { style: styles.tableCellText }, fmtTime(entry.time_in))
            ),
            React.createElement(
              View,
              { style: styles.colTimeOut },
              React.createElement(Text, { style: styles.tableCellText }, fmtTime(entry.time_out))
            ),
            React.createElement(
              View,
              { style: styles.colHours },
              React.createElement(
                Text,
                { style: styles.tableCellTextRight },
                fmtHours(entry.total_hours)
              )
            ),
            React.createElement(View, { style: styles.colNotes })
          )
        ),
        // Totals row
        React.createElement(
          View,
          { style: styles.totalsRow },
          React.createElement(
            View,
            { style: styles.totalsLabelCell },
            React.createElement(Text, { style: styles.totalsLabelText }, 'Total Hours')
          ),
          React.createElement(
            View,
            { style: styles.totalsValueCell },
            React.createElement(
              Text,
              { style: styles.totalsValueText },
              fmtHours(totalHours)
            )
          ),
          React.createElement(View, { style: styles.totalsEmptyCell })
        )
      ),

      // ---- Earnings Summary (if NTL rate available) ----
      ...(earnings !== null
        ? [
            React.createElement(
              View,
              { style: styles.earningsRow },
              React.createElement(
                View,
                { style: styles.earningsBox },
                React.createElement(
                  View,
                  { style: styles.earningsItem },
                  React.createElement(Text, { style: styles.earningsLabel }, 'NTL Rate'),
                  React.createElement(
                    Text,
                    { style: styles.earningsValue },
                    fmtCurrency(data.ntlRate!)
                  )
                ),
                React.createElement(
                  View,
                  { style: styles.earningsItem },
                  React.createElement(Text, { style: styles.earningsLabel }, 'Total Hours'),
                  React.createElement(
                    Text,
                    { style: styles.earningsValue },
                    fmtHours(totalHours)
                  )
                ),
                React.createElement(
                  View,
                  { style: styles.earningsItem },
                  React.createElement(Text, { style: styles.earningsLabel }, 'Gross Earnings'),
                  React.createElement(
                    Text,
                    { style: styles.earningsValue },
                    fmtCurrency(earnings)
                  )
                )
              )
            ),
          ]
        : []),

      // ---- Signature Block ----
      React.createElement(Text, { style: styles.sectionLabel }, 'Signatures'),
      React.createElement(
        View,
        { style: styles.signaturesContainer },

        // Staff signature
        React.createElement(
          View,
          { style: styles.signatureBox },
          React.createElement(
            View,
            { style: styles.signatureHeader },
            React.createElement(Text, { style: styles.signatureHeaderText }, 'Employee Signature')
          ),
          React.createElement(
            View,
            { style: styles.signatureBody },
            data.staffSignature
              ? React.createElement(
                  React.Fragment,
                  null,
                  React.createElement(
                    Text,
                    { style: styles.signatureNameLabel },
                    'Signed electronically as:'
                  ),
                  React.createElement(
                    Text,
                    { style: styles.signatureName },
                    data.staffSignature
                  ),
                  React.createElement(
                    Text,
                    { style: styles.signatureTimestamp },
                    fmtTimestamp(data.staffSignedAt)
                  )
                )
              : React.createElement(
                  Text,
                  { style: styles.signaturePending },
                  'Signature pending'
                )
          )
        ),

        // Signee signature
        React.createElement(
          View,
          { style: styles.signatureBox },
          React.createElement(
            View,
            { style: styles.signatureHeader },
            React.createElement(
              Text,
              { style: styles.signatureHeaderText },
              'Authorized Signee Signature'
            )
          ),
          React.createElement(
            View,
            { style: styles.signatureBody },
            data.signeeSignature
              ? React.createElement(
                  React.Fragment,
                  null,
                  React.createElement(
                    Text,
                    { style: styles.signatureNameLabel },
                    data.signeeName
                      ? `Signed by ${data.signeeName} as:`
                      : 'Signed electronically as:'
                  ),
                  React.createElement(
                    Text,
                    { style: styles.signatureName },
                    data.signeeSignature
                  ),
                  React.createElement(
                    Text,
                    { style: styles.signatureTimestamp },
                    fmtTimestamp(data.signeeSignedAt)
                  )
                )
              : React.createElement(
                  Text,
                  { style: styles.signaturePending },
                  'Awaiting signee signature'
                )
          )
        )
      ),

      // ---- Footer ----
      React.createElement(
        View,
        { style: styles.footer, fixed: true },
        React.createElement(
          Text,
          { style: styles.footerText },
          'Generated by Norwich Public Schools Timesheet System'
        ),
        React.createElement(
          View,
          { style: styles.footerRight },
          React.createElement(
            Text,
            { style: styles.footerText },
            `Generated: ${generatedAt}`
          ),
          React.createElement(
            Text,
            {
              style: styles.pageNumber,
              render: ({ pageNumber, totalPages }: { pageNumber: number; totalPages: number }) =>
                `Page ${pageNumber} of ${totalPages}`,
            }
          )
        )
      )
    )
  )
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Generates a single timecard PDF and returns it as a Buffer.
 *
 * @param data - All data needed to render the timecard PDF
 * @returns Promise<Buffer> — ready for HTTP response or Supabase Storage upload
 *
 * @example
 * const pdfBuffer = await generateTimecardPdf(timecardData)
 * // In a Route Handler:
 * return new Response(pdfBuffer, {
 *   headers: {
 *     'Content-Type': 'application/pdf',
 *     'Content-Disposition': `attachment; filename="timecard-${staffName}.pdf"`,
 *   },
 * })
 */
export async function generateTimecardPdf(data: TimecardPdfData): Promise<Buffer> {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const doc = React.createElement(TimecardDocument, { data }) as any
  const buffer = await renderToBuffer(doc)
  return Buffer.from(buffer)
}

/**
 * Generates a filename for a timecard PDF.
 * Format: timecard_<StaffName>_<PayPeriodLabel>.pdf
 */
export function getTimecardPdfFilename(
  staffName: string,
  payPeriodLabel: string
): string {
  const safeName = staffName.replace(/[^a-zA-Z0-9]/g, '_').replace(/_+/g, '_')
  const safePeriod = payPeriodLabel.replace(/[^a-zA-Z0-9]/g, '_').replace(/_+/g, '_')
  return `timecard_${safeName}_${safePeriod}.pdf`
}
